# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "nvd-model/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "diesel::sql_types::SqlType","crate::types::*"]

[migrations_directory]
dir = "nvd-model/migrations"
